### ISSUE TITLE
STA9750 cliu98 MiniProject #01

### ISSUE THREAD

**Issue by cliu98** [cliu98/STA9750-2024-FALL#2]
Hi @michaelweylandt!

I've uploaded my work for MiniProject #01 - check it out!

https://cliu98.github.io/STA9750-2024-FALL/mp01.html

**Comment by michaelweylandt** [comment]
Thanks @cliu98 !

Peer Feedback:

- @SethKauf
- @camilomartinez777
- @aaronkcooper
- @laurencardieri

It is now time for the peer feedback round for Mini-Project #01. Please
review @cliu98's submission for this mini-project and provide peer feedback.

Using the rubric at https://michael-weylandt.com/STA9750/miniprojects/mini01.html#rubric,
please grade their submission out of a total of 50 points.

For each of the five categories, please give them a separate score and provide
a total (sum) score across the entire assignment. Feel free to assign extra
credit if you feel it is warranted (following the rubric).

If you give a score of less than 5 for any category, please provide a suggestion
for improvement. (You can also give suggestions for any element they did well -
more feedback is always great!)

As you go through this peer feedback exercise, think about what you particularly
like about this submission and how you can incorporate that approach in your future
work. If something is particularly insightful or creative, give some kudos!

Evaluators: This should take you around 15 minutes per peer feedback. You are
not required to engage in substantial back-and-forth with @cliu98, but you are of course
welcome to initiate a discussion.

@cliu98: please engage fully with your peers. They are here to help you!

Submission URL should be: https://cliu98.github.io/STA9750-2024-FALL/mp01.html

Feel free to link to other repos, the course documentation, or other useful
examples.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by SethKauf** [comment]
Hi @cliu98 ,

Awesome project! Here's my breakdown of my grade for you:

**Written Communication: 10/10**
I love how you've laid out this project from A-Z and how you emphasized each portion. Re-using some of the LaTeX from the question prompts to make it pop more was a nice touch. The way you incorporated warnings/notes so I could expand if I wanted to see them but they weren't imposing/throwing off the tempo of the project was really well done. Overall, I really like this project's structure.

**Project Skeleton: 10/10**
The code runs as-expected and answers the question prompts.

**Formatting & Display: 9/10**
Some of the data tables could've displayed a bit better, but overall really good job with these.

**Code Quality: 8/10**
The code runs and produces the expected outputs. However, there are three things I think can be improved on for next time:
1. Comments: you had the equivalent to comments in some of your Markdown, but I think they can really be better used in the code itself
2. Repetitiveness: Calling the filter function multiple times consecutively in the same pipe, for example
3. There were several instances where you re-imported a library (specifically tidyverse and dplyr). You also only use the `if (!require("<PACKAGE>")) install.packages("<PACKAGE>")` for two libraries, which isn't the biggest deal, but it's a bit inconsistent.

**Data Preparation: 10/10**
N/A


**Overall: 47/50**
I really liked this project and thought you did a great job setting the problems up and explaining them one at a time. Your creative use of Markdown/LaTeX especially with tangent-thoughts was well done. I think your code could be a bit cleaner and more commented on.

Really good job!

**Comment by laurencardieri** [comment]
Hi Chris! 

Here is my feedback for Mini-Project 1: 

Written Communication: 10/10- Everything was really well-explained! I like how you even used hyperlinks to access the data that you used. 

Project Skeleton: 10/10 - All questions asked in the prompt was answered. 

Formatting and Display: 11/10- Your page was very pleasing to look at. I liked how you added little sections for notes/the questions asked, especially with the drop downs! 

Code Quality- 10/10 - I believe your code was very well-done. I also liked how you thought to check for any NA values to consider before continuing. 

Data Preparation- 10/10

Total Score: 51/50. Great job!

**Comment by aaronkcooper** [comment]
Hi @cliu98,
Really nice job on the first Mini-Project! Here is my breakdown of feedback:
**Written Communication: 10/10**
I really liked the overall flow of the project, especially the added blocks of tips and warnings utilizing the features of quarto really well. Great addition adding the initial question prompts from the assignment to really highlight the goals behind your analysis.

**Project Skeleton: 10/10**
All questions were answered as required.

**Formatting and Display: 9/10**
I think it would have been more effective to utilize datatables instead of tibbles, presentation wise, other then that nice job.

**Code Quality: 9/10**
If all your aim is in a block of code is to show the output of some result, there probably is no need to store a table as a variable then print it out using `print`. If you aren't using that table again it probably is more efficient to just print the output which will automatically be a tibble. 

**Data Preparation: 10/10**

**Total Score: 48/50**
Great Job!

**Comment by charles-ramirez** [comment]
Hi @camilomartinez777,

This is just a reminder that your peer review is due at 11:45 pm.

**Comment by camilojourney** [comment]
Hi @cliu98,
Great job on the first Mini-Project! Here’s my feedback:

Written Communication: 10/10
The project flowed well, and I liked the tips and warnings you included. Adding the original questions was a nice touch.

Project Structure: 9/10
All questions were answered, but a few parts could be simplified.

Formatting: 9/10
Using datatables would look better than tibbles, but overall it was good.

Code Quality: 9/10
If a block only shows results, no need to save it as a variable first—just print it directly.

Data Preparation: 10/10

Total Score: 47/50
Nice work!
